-- Database Schema for CRM (PostgreSQL / Supabase)

-- Enable UUID extension if not already enabled (though we use Text/Serial for simplicity to match local mock for now, can upgrade later)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS roles (
  id TEXT PRIMARY KEY, -- 'admin', 'user', 'viewer'
  name TEXT NOT NULL,
  description TEXT,
  permissions JSONB -- PostgreSQL uses JSONB for JSON data
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role_id TEXT REFERENCES roles(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  client_code TEXT,
  subdomain TEXT,
  product_type TEXT, -- Dr.Ease, EasePos
  package TEXT, -- Starter, Standard, Elite, Pro, Demo
  usage_status TEXT, -- Active, Trial, Inactive, Canceled
  business_type TEXT,
  contract_number TEXT,
  contract_start DATE,
  contract_end DATE,
  sales_name TEXT,
  contact_name TEXT,
  contact_phone TEXT,
  note TEXT,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  modified_by TEXT,
  modified_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS branches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  is_main BOOLEAN DEFAULT FALSE,
  address TEXT,
  status TEXT -- รอการติดตั้ง, กำลังติดตั้ง, ติดตั้งเสร็จ
);

CREATE TABLE IF NOT EXISTS installations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  branch_name TEXT,
  status TEXT, -- Pending, Installing, Completed
  requested_by TEXT,
  requested_at TIMESTAMPTZ DEFAULT NOW(),
  assigned_dev TEXT,
  completed_at TIMESTAMPTZ,
  notes TEXT,
  installation_type TEXT, -- new, branch
  modified_by TEXT,
  modified_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS issues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_number TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  branch_name TEXT,
  severity TEXT, -- ต่ำ, ปานกลาง, สูง, วิกฤต
  status TEXT, -- แจ้งเคส, กำลังดำเนินการ, เสร็จสิ้น
  type TEXT,
  description TEXT,
  attachments JSONB, -- JSON Array for file metadata
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  modified_by TEXT,
  modified_at TIMESTAMPTZ
);

-- Optional: Create some indexes for performance
CREATE INDEX IF NOT EXISTS idx_customers_name ON customers(name);
CREATE INDEX IF NOT EXISTS idx_issues_status ON issues(status);
CREATE INDEX IF NOT EXISTS idx_installations_status ON installations(status);

CREATE TABLE IF NOT EXISTS activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  customer_name TEXT,
  title TEXT NOT NULL,
  activity_type TEXT, -- Call, Meeting, Email, Onsite, Other
  content TEXT,
  status TEXT, -- Open, In Progress, Closed
  sentiment TEXT, -- Positive, Neutral, Negative
  follow_up_date TIMESTAMPTZ,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  modified_by TEXT,
  modified_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_activities_customer_id ON activities(customer_id);

CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_number TEXT UNIQUE NOT NULL,
  product TEXT, -- Dr.Ease, Ease POS
  source TEXT, -- ยิงแอด, เซลล์หา, พาร์ทเนอร์, บริษัทหา
  lead_type TEXT, 
  sales_name TEXT,
  customer_name TEXT,
  phone TEXT,
  received_date DATE,
  notes TEXT,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  modified_by TEXT,
  modified_at TIMESTAMPTZ
);
